### ISSUE TITLE
Incorrect order in introduction

### ISSUE THREAD

**Issue by rosen-vladimirov** [telerik/xaml-docs#130]
In introduction.md it looks like controls are ordered in alphabetical order. But DragDropManager is the first control, maybe it should be moved down to its correct place.
Also there's a typo in the end of the article - in http://docs.telerik.com/devtools/wpf/introduction#help-us-improve-wpf-documentation under ##Submit a New Issue at GitHub ```docs``` is spelled as ```docKs```

**Comment by APopatanasov** [comment]
Thank you for your feedback. The Introduction article is fixed now.

**Comment by rosen-vladimirov** [comment]
Well it looks like it is not - for Silverlight it is still on first place :cry:  :crying_cat_face:
