### ISSUE TITLE
Contradiction for styling GridViewCheckBoxColumn 

### ISSUE THREAD

**Issue by janschreier** [telerik/xaml-docs#2014]
here
https://docs.telerik.com/devtools/wpf/controls/radgridview/columns/columntypes/checkbox-column
it says at the bottom:
"Since the GridViewCheckBoxColumn is specially designed to dispay checkboxes, setting its CellTemplate, CellEditTemplate, CellTemplateSelector and CellEditTemplateSelector is not supported. For such requirements, you can use a GridViewDataColumn."

which is contradicted by the pure existence of this entire page:
https://docs.telerik.com/devtools/wpf/controls/radgridview/styles-and-templates/columns-styling-checkboxcolumn

**Comment by martinivanoff** [comment]
Hello Jan,

Excuse us for the late notice. And thank you for the feedback.

May I ask you to elaborate a bit more on this question? I am not sure that I understand your concern. The GridViewCheckBoxColumn was, indeed, designed to show a CheckBox. The purpose of the styling article is to show only how to customize the  internal CheckBox control. The article provides information also how to replace the CheckBox entire ControlTemplate which could lead to visually new control, but we do not encourage such modifications unless they match the CheckBox's look and feel, or at least something similar.

Regards,
Martin Ivanov
WPF Team

**Comment by janschreier** [comment]
Hi Martin,
maybe the pull request makes it clearer and keeps the info that one should not be to aggressive when using styles. 
But when you write
 "The article provides information also how to replace the CheckBox entire ControlTemplate which could lead to visually new control, but we do not encourage such modifications unless they match the CheckBox's look and feel, or at least something similar."

I wonder if that should be a warning on this page: https://docs.telerik.com/devtools/wpf/controls/radgridview/styles-and-templates/columns-styling-checkboxcolumn

br, Jan

**Comment by martinivanoff** [comment]
Hi Jan,

Please excuse me for the delayed answer. And thank you for the commit. Indeed, this makes your idea more clear. We will extend the note based on your description. Also, we will consider if such a warning should be included in the article.

Regards,
Martin Ivanov,
Technical Support Engineer, WPF Team
