### ISSUE TITLE
Assembly list and figure mismatch

### ISSUE THREAD

**Issue by Jogge** [telerik/xaml-docs#2234]
Assembly list does not match the assemblies in the figure.

![image](https://user-images.githubusercontent.com/15981279/97433003-190d9a80-191d-11eb-80ec-9feea308536f.png)

https://github.com/telerik/xaml-docs/blob/master/controls/raddiagram/getting-started.md

**Comment by DinkoK** [comment]
Thank you for the provided feedback. You are right that the image is not relevant, and it isn't clear enough which assemblies are required and which ones are optional. We have logged an internal item to update this section of the RadDiagram Getting Started article. We will keep you updated on this.

**Comment by martinivanoff** [comment]
Hello Jogge,

We've already updated the article and the change will go live after it passes the review and the documentation is uploaded. 

Regards,
Martin Ivanov
Telerik WPF Team
