### ISSUE TITLE
Link to a 404 page in Diagram documentation

### ISSUE THREAD

**Issue by JarRami** [telerik/xaml-docs#2826]
In the [Rad diagram documentation](https://docs.telerik.com/devtools/wpf/controls/raddiagram/getting-started), near the top of the page, there is a box with the text 

"You can find more info about the Telerik UI for WPF dependencies in the [Controls Dependencies](http://www.telerik.com/help/wpf/installation-installing-controls-dependencies-wpf.html) help article."

For me atleast, the link seems to return a 404 page

**Comment by martinivanoff** [comment]
Thank you for the report. We've [fixed this](https://github.com/telerik/xaml-docs/commit/01e313e322410ae0baa4ed74a964b7890db532c1) and will be available with the next upload of the help documentation.
