### ISSUE TITLE
Added new article about grouping items in RadListBox

### ISSUE THREAD

**Issue by APopatanasov** [telerik/xaml-docs#364]

**Comment by erikruth** [comment]
I don’t see a specific article to edit in #364. Do you want me to edit all of the articles you made changes to when you replaced SDK with Developer Examples? I see some small changes in a few documents that need corrections.

**Comment by APopatanasov** [comment]
Hi Erik,
I added a new article in the "How To" section of RadListBox named "How to group items". I wrote it in the last minute before SP1 Q3 2015 was officially released and merged it before you could check it. Could you, please check it now?

**Comment by erikruth** [comment]
Did you get the pull request? I edited this and opened one.

**Comment by APopatanasov** [comment]
I could not see any pull request. Could you please, try again or if it is easy for you just paste the made changes here and I will correct the article by myself? :smile:

**Comment by erikruth** [comment]
I just edited it again and made a pull request. If you do not see the pull request, let me know. I saved my edits to a text file and I can email it to you.

**Comment by APopatanasov** [comment]
I found the made by you changes - you have committed them inside your branch named "erikruth-patch-1". In order to made them also visible in master you should now made a pull request to master. However, do not worry about this I will made the changes in my branch and will merge it with master. Thanks a lot for the help I will close the Issue.

**Comment by erikruth** [comment]
Thanks. Sorry if I made it in the wrong place.
