### ISSUE TITLE
Custom Column Editor article for RadGridView

### ISSUE THREAD

**Issue by PetyaSotirova** [telerik/xaml-docs#369]
Please review the new topic for RadGridView at https://github.com/telerik/xaml-docs/blob/master/controls/radgridview/columns/how-to/create-custom-column-editor.md .

Thank you for the specific link to what you needed edited. I finished editing and made minor copy editing changes and merged back to the master because there were no comments for you to review. However, the two links at the very end of the article produce HTTP 500 errors.

**Comment by erikruth** [comment]
Thank you for the specific link to what you needed edited. I finished editing and made minor copy editing changes and merged back to the master because there were no comments for you to review. However, the two links at the very end of the article produce HTTP 500 errors.

**Comment by PetyaSotirova** [comment]
Thank you, Erik. The links are expected to produce errors if you're looking at the article in GitHub's UI. When the documentation is served locally or on the server, they work and I double-checked this just in case.
I'm closing the issue.
