### ISSUE TITLE
Copy a Worksheet Article

### ISSUE THREAD

**Issue by PetyaSotirova** [telerik/xaml-docs#446]
Original commit is [here](https://github.com/telerik/xaml-docs/pull/407) and as far as I'm aware you haven't reviewed it.
The article can be seen and edited [here](https://github.com/telerik/xaml-docs/blob/master/controls/radspreadprocessing/working-with-worksheets/copy-worksheet.md).

**Comment by erikruth** [comment]
I edited this on March 4. Feel free to merge the changes and close this issue.
