### ISSUE TITLE
TileList Selection Article

### ISSUE THREAD

**Issue by PetyaSotirova** [telerik/xaml-docs#447]
Original commit is [here](https://github.com/telerik/xaml-docs/pull/438) and I haven't assigned it to you at all as I finished the article late. 
You can review and edit it from [here](https://github.com/telerik/xaml-docs/blob/master/controls/radtilelist/features/selection.md).

**Comment by erikruth** [comment]
Reviewed. No changes from me.

**Comment by PetyaSotirova** [comment]
Thank you.
