### ISSUE TITLE
Showing a File article

### ISSUE THREAD

**Issue by TanyaDimitrova** [telerik/xaml-docs#596]
Erik, I added the _Setting Reading Mode_ section but didn't assign it to you as we had to merge. Could you please check it? You could find the article [here](https://github.com/telerik/xaml-docs/blob/master/controls/radpdfviewer/showing-a-file.md).

**Comment by erikruth** [comment]
I edited this on May 15.

**Comment by TanyaDimitrova** [comment]
Thank you.
