### ISSUE TITLE
Section Columns articles

### ISSUE THREAD

**Issue by TanyaDimitrova** [telerik/xaml-docs#605]
These articles were merged before you can preview them. Could you check them and let me know if you have any comments on the content?

Here are the links to the exact articles:
[Section Columns API](https://github.com/telerik/xaml-docs/blob/master/controls/radrichtextbox/features/section-columns.md)
[Section Columns UI](https://github.com/telerik/xaml-docs/blob/master/controls/radrichtextbox/ui-for-applying-rich-text-formatting/section-columns.md)

**Comment by erikruth** [comment]
I edited both. The API article had minor changes and one comment to address. The UI article was very good. I had no edits to it.
Erik

**Comment by TanyaDimitrova** [comment]
Thank you, Erik. I addressed the comment and will close this issue.
