### ISSUE TITLE
How to use Upgrade API Analyzer tool article

### ISSUE THREAD

**Issue by kerpecheva** [telerik/xaml-docs#609]
Hi Erik,
I added a new article about the Upgrade API Analyzer tool, I didn't assign it to you as we had to merge. Could you please check it? You can find it at the following link:
[https://github.com/telerik/xaml-docs/blob/master/upgrade-api-analyzer.md](https://github.com/telerik/xaml-docs/blob/master/upgrade-api-analyzer.md)

**Comment by erikruth** [comment]
I edited this on May 15.

**Comment by kerpecheva** [comment]
Thank you, Erik. I am closing the issue.
