### ISSUE TITLE
Add GitHub repo description and URL

### ISSUE THREAD

**Issue by dandv** [telerik/xaml-docs#94]
This repo shows on the first page at https://github.com/telerik

Example:

[![image](https://cloud.githubusercontent.com/assets/33569/4949884/c2b69bde-6651-11e4-88eb-8fdf8e8c9f0a.png)](https://github.com/dandv/meteor-jquery-rateit)

**Comment by kalintodorov** [comment]
Thanks for bringing this to our attention - added description. If you share your Telerik account (or send us ticket) we will update your Telerik points for your involvement.

**Comment by dandv** [comment]
Hi @kalintodorov. My Telerik account is under this email: ddascalescu AT gmail.com. I've also contributed to [kendo-ui-core](https://github.com/telerik/kendo-ui-core/issues?q=author%3Adandv) and [kendo-docs](https://github.com/telerik/kendo-docs/issues?q=author%3Adandv).

**Comment by kalintodorov** [comment]
Hi @dandv, I have updated your Telerik points.

Regards,
Kalin
